package template

type DescriptionMsg string

const (
	DescriptionMsgSetUpSuccess            DescriptionMsg = "設定成功!"
	DescriptionMsgNoProblem               DescriptionMsg = "沒問題!"
	DescriptionMsgOpen                    DescriptionMsg = "開啟"
	DescriptionMsgClose                   DescriptionMsg = "關閉"
	DescriptionMsgUpdateAlermSuccess      DescriptionMsg = "更新成功, 已將%s推播功能%s"
	DescriptionMsgAskSendWeight           DescriptionMsg = "請輸入今日體重"
	DescriptionMsgAskSendSleep            DescriptionMsg = "請輸入今日睡眠時數"
	DescriptionMsgAskSendWater            DescriptionMsg = "請輸入今日飲水量"
	DescriptionMsgAskSetNewTargetWeight   DescriptionMsg = "請輸入新的目標體重(公斤)"
	DescriptionMsgAIAnalyze               DescriptionMsg = "AI 分析中，請稍後"
	DescriptionMsgSignUpSuccess           DescriptionMsg = "註冊成功!"
	DescriptionMsgMeal                    DescriptionMsg = "餐點"
	DescriptionMsgMealName                DescriptionMsg = "名稱"
	DescriptionMsgAskSendMealName         DescriptionMsg = "請輸入%s餐點名稱"
	DescriptionMsgWeightUpdate            DescriptionMsg = "體重已更新 %.1f 公斤"
	DescriptionMsgWeightFormatError       DescriptionMsg = "體重格式錯誤，請重新輸入 ex. 70.5"
	DescriptionMsgSleepUpdate             DescriptionMsg = "睡眠時數已更新 %.1f 小時"
	DescriptionMsgSleepFormatError        DescriptionMsg = "睡眠時數格式錯誤，請重新輸入 ex. 7.5"
	DescriptionMsgWaterUpdate             DescriptionMsg = "飲水量已更新 %.1f 毫升"
	DescriptionMsgWaterFormatError        DescriptionMsg = "飲水量格式錯誤，請重新輸入 ex. 2000"
	DescriptionMsgTargetWeightUpdate      DescriptionMsg = "目標已更新為 %.1f 公斤，預計 %d 個月達成!"
	DescriptionMsgAskSetTargetWeight      DescriptionMsg = "請輸入目標體重 ex. 65.0"
	DescriptionMsgTargetTimeFormatError   DescriptionMsg = "目標時間格式錯誤，請重新輸入 ex. 3"
	DescriptionMsgAskSetTargetTime        DescriptionMsg = "請輸入目標時間(月) ex. 3"
	DescriptionMsgTargetWeightFormatError DescriptionMsg = "目標體重格式錯誤，請重新輸入 ex. 65.0"
	DescriptionMsgGender                  DescriptionMsg = "性別"
	DescriptionMsgMale                    DescriptionMsg = "男"
	DescriptionMsgFemale                  DescriptionMsg = "女"
	DescriptionMsgHeight                  DescriptionMsg = "身高"
	DescriptionMsgWeight                  DescriptionMsg = "體重"
	DescriptionMsgAge                     DescriptionMsg = "年齡"
	DescriptionMsgTargetWeight            DescriptionMsg = "目標體重"
	DescriptionMsgTargetTime              DescriptionMsg = "目標時間"
	DescriptionMsgBasicInfo               DescriptionMsg = "基本資料"
	DescriptionMsgAskSetGender            DescriptionMsg = "請輸入性別(男/女)"
	DescriptionMsgAskHeight               DescriptionMsg = "請輸入身高(公分) ex. 175.5"
	DescriptionMsgAskWeight               DescriptionMsg = "請輸入體重(公斤) ex. 70.5"
	DescriptionMsgAskAge                  DescriptionMsg = "請輸入年齡 ex. 25"
	DescriptionMsgGenderFormatError       DescriptionMsg = "性別格式錯誤，請重新輸入(男/女)"
	DescriptionMsgHeightFormatError       DescriptionMsg = "身高格式錯誤，請重新輸入 ex. 175.5"
	DescriptionMsgAgeFormatError          DescriptionMsg = "年齡格式錯誤，請重新輸入 ex. 25"
	DescriptionMsgWelcomeSignUp           DescriptionMsg = "歡迎使用營養師機器人，請依序輸入您的身高(公分)、體重(公斤)、年齡、性別(男/女)以完成註冊"
	DescriptionMsgUploadMeal              DescriptionMsg = "上傳餐點"
	DescriptionMsgUploadMealIntro         DescriptionMsg = "請點擊下方選單開始上傳餐點"
	DescriptionMsgStartUse                DescriptionMsg = "歡迎開始使用營養紀錄助理！\n我會協助你記錄每天的飲食、飲水量、睡眠與體重，並根據你的目標整理每日飲食報告，幫助你更清楚掌握熱量、蛋白質與營養狀況。\n你可以先從以下幾件事開始：\n\n1.  上傳餐點照片\n點選「上傳餐點」，拍下早餐、午餐、晚餐或點心，我會協助分析餐點內容與營養估算。\n\n2.  記錄飲水量\n每天記得回報飲水狀況，幫助我追蹤你的水分攝取是否足夠。 \n\n3.  記錄睡眠與體重\n早上可以填寫睡眠時間與今日體重，讓飲食建議更貼近你的身體狀態。 \n\n4.  查看每日報告\n點選「每日報告」，可以查看今天的飲食總結、目標達成度與改善建議。 \n\n5.  調整個人目標\n如果你的目標是減脂、增肌或維持體重，可以到「改變目標」更新設定。\n\n從今天開始，只要照常吃、照常記錄，我會幫你把每天的飲食狀況整理成容易理解的健康建議。\n先從記錄今天第一餐開始吧！"
)

func (m DescriptionMsg) String() string {
	return string(m)
}
